# Generated by Django 4.1.7 on 2023-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(default='No description has been provided for this event yet.'),
        ),
    ]
