# Generated by Django 4.1.7 on 2023-04-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age',
            field=models.CharField(choices=[('18+', '18+'), ('21+', '21+'), ('All ages welcome', 'All ages welcome')], default='18+', max_length=30),
        ),
    ]
