# Generated by Django 4.1.7 on 2023-03-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event", options={"ordering": ("event_date_time",)},
        ),
    ]
