# Generated by Django 4.1.7 on 2023-03-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_friendrequest_friendlist"),
    ]

    operations = [
        migrations.RemoveField(model_name="friendrequest", name="receiver",),
        migrations.RemoveField(model_name="friendrequest", name="sender",),
        migrations.DeleteModel(name="FriendList",),
        migrations.DeleteModel(name="FriendRequest",),
    ]
