# Generated by Django 4.1.7 on 2023-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Party'), (1, 'Concert'), (2, 'Comedy Show'), (3, 'Other')], default=0),
        ),
    ]
