# Generated by Django 4.1.7 on 2023-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age',
            field=models.IntegerField(choices=[(0, '18+'), (1, '21+'), (2, 'All ages welcome')], default=0),
        ),
    ]
