# Generated by Django 4.1.7 on 2023-02-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_event_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Party', 'Party'), ('Concert', 'Concert'), ('Comedy Show', 'Comedy Show'), ('Other', 'Other')], default='Party', max_length=15),
        ),
    ]
